# Cập nhật file application.yaml của bạn
server:
  port: 5000
  servlet:
    context-path: /webchat

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/social_network?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: nguyenphuoc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

jwt:
  signerKey: "liawejhgpi9q7wtryhfilajsdbvoqf837yrhfPISWYG9QURW7RT"
  valid-duration: 30
  refreshable-duration: 120

# Cloudinary Configuration
#cloudinary:
#  cloud-name: ${CLOUDINARY_CLOUD_NAME:your-cloud-name}
#  api-key: ${CLOUDINARY_API_KEY:your-api-key}
#  api-secret: ${CLOUDINARY_API_SECRET:your-api-secret}
cloudinary:
  cloud-name: "dawxdwbjk"
  api-key: "814829166217436"
  api-secret: "PDx6EKACQZYEVIM-5Nmt17Mzivw"